name: Build
on:
  push:
    #    tags:
    #      - '*'   # 仅在推送 tag 时触发
    branches:
      - dev
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-latest ] #  todo: macos-latest, no macos env.
        goarch: [ amd64, arm64 ]
    runs-on: ${{ matrix.os }}
    env:
      CMD_PATH: ./cmd/blive
      EXE: blive-${{ matrix.os }}-${{matrix.goarch}}
      TAG: ${{ github.ref_name }}     # tag 名称，例如 v1.2.3
      GITHASH_FULL: ${{ github.sha }} # 完整 commit sha
      CGO_ENABLED: 0
      GOARCH: ${{matrix.goarch}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
      - name: Install Go Dependencies
        run: |
          go mod tidy

      - name: Build (non-Windows)
        if: runner.os != 'Windows'
        run: |
          set -e
          echo "Runner OS: $RUNNER_OS"
          echo "Building ${EXE} (GOOS=$GOOS GOARCH=$GOARCH)"
          go build -trimpath -o "${EXE}" -ldflags "-X main.version=${TAG} -X main.gitHash=${GITHASH_FULL}" "${CMD_PATH}"
      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Runner OS: $env:RUNNER_OS"
          Write-Host "Building $out (GOOS=$($env:GOOS) GOARCH=$($env:GOARCH))"
          go build -trimpath -o "${env:EXE}.exe" -ldflags "-X main.version=$($env:TAG) -X main.gitHash=$($env:GITHASH_FULL)" $env:CMD_PATH

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blive-${{ matrix.os }}-${{ matrix.goarch }}
          path: |
            blive-${{ matrix.os }}-${{ matrix.goarch }}
            blive-${{ matrix.os }}-${{ matrix.goarch }}.exe